name: Update Icon

on:
  repository_dispatch:
    types: [Update-Icons]

jobs:
  update-icon:
    runs-on: ubuntu-latest
    steps:
      - name: Global Git Configuration
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      # トークンを生成    
      - name: Generate github token for GitHub App
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}    

      # "nogson/figmaExportSVG"リポジトリをチェックアウト
      - name: Checkout figmaExportSVG's repo
        uses: actions/checkout@v3
        with:
          repository: "nogson/figmaExportSVG"
          fetch-depth: 0

      # Node.jsのセットアップ
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      # 依存関係のインストール
      - name: Install
        run: npm ci

      # アイコンの更新
      - name: Update Icon
        run: |
          FIGMA_TOKEN=${{ secrets.FIGMA_TOKEN }} FIGMA_FILE_KEY=${{ secrets.FIGMA_FILE_KEY }} PLATFORM=${{github.event.client_payload.platform}} npm run build:icon

      # "nogson/takePR"リポジトリをチェックアウト
      - name: Checkout takePR's repo
        uses: actions/checkout@v3
        with:
          repository: "nogson/takePR"
          token: ${{ steps.generate_token.outputs.token }}
          fetch-depth: 0
          path: "takePR"

      # 更新されたアイコンを"nogson/takePR"リポジトリにコピー
      - name: Copy updated icons to takePR's repo
        run: cp -R ./src/PBaseNavi/* takePR/
      # プルリクエストの作成
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.generate_token.outputs.token }}
          commit-message: "feat: update icons"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: feat/update-icons
          branch-suffix: timestamp
          delete-branch: true
          title: "feat: update icons"
          body: Icons has been updated
          path: "takePR"
