name: Update Variables

on:
  repository_dispatch:
    types: [Update-Variables]

jobs:
  update-icon:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ["nogson/takePR"  ]
    steps:
      - name: Global Git Configuration
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      # トークンを生成
      - name: Generate github token for GitHub App
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      # "nogson/figmaDeignTokenToGithub"リポジトリをチェックアウト
      - name: Checkout figmaDeignTokenToGithub's repo
        uses: actions/checkout@v4
        with:
          repository: "nogson/figmaDeignTokenToGithub"
          fetch-depth: 0

      # Node.jsのセットアップ
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      # 依存関係のインストール
      - name: Install
        run: npm ci

      # トークンを生成
      - name: Prepare Payload
        run: |
          mkdir -p ./styleDictionary/tokens
          echo '${{ toJson(github.event.client_payload.data) }}' > ./styleDictionary/tokens/variables.json

      - name: Build tokens and remove variables.json
        run: |
          npm run build:tokens
          rm ./styleDictionary/tokens/variables.json

      # "nogson/takePR"リポジトリをチェックアウト
      - name: Checkout takePR's repo
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repo }}
          token: ${{ steps.generate_token.outputs.token }}
          fetch-depth: 0
          path: repo

      # 更新されたvariablesを"nogson/takePR"リポジトリにコピー
      - name: Copy updated variables to takePR's repo
        run: cp -R ./build/* repo/

      # プルリクエストの作成
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.generate_token.outputs.token }}
          commit-message: "feat: update variables"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: feat/update-variables
          branch-suffix: timestamp
          delete-branch: true
          title: "feat: update variables"
          body: Variables has been updated
          path: repo
