name: Update Icon

on:
  repository_dispatch:
    types: [Update-Icons]

jobs:
  update-icon:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Generate GitHub Token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Checkout Repositories
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.client_payload.repository }}
          token: ${{ steps.generate_token.outputs.token }}
          fetch-depth: 0
          path: ${{ github.event.client_payload.path }}

      - name: Install Dependencies
        run: npm ci

      - name: Update Icons
        env:
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
          FIGMA_FILE_KEY: ${{ secrets.FIGMA_FILE_KEY }}
          PLATFORM: ${{ github.event.client_payload.platform }}
        run: npm run build:icon && ls -la ./src/PBaseNavi/

      - name: Copy Icons to takePR Repo
        run: cp -R ./src/PBaseNavi/* takePR/

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.generate_token.outputs.token }}
          commit-message: "feat: update icons"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: feat/update-icons
          branch-suffix: timestamp
          delete-branch: true
          title: "feat: update icons"
          body: "Icons have been updated."
          path: "takePR"
