name: Update Icon

on:
  repository_dispatch:
    types: [Update-Icons]

jobs:
  update-icon:
    runs-on: ubuntu-latest
    steps:
      - name: Global Git Configuration
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      # トークンを生成
      - name: Generate github token for GitHub App
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      # "nogson/figmaExportSVG"リポジトリをチェックアウト
      - name: Checkout figmaExportSVG's repo
        uses: actions/checkout@v3
        with:
          repository: "nogson/figmaExportSVG"
          fetch-depth: 0

      # Node.jsのセットアップ
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      # 依存関係のインストール
      - name: Install
        run: npm ci

      # アイコンの更新
      - name: Update Icon
        run: |
          FIGMA_TOKEN=${{ secrets.FIGMA_TOKEN }} FIGMA_FILE_KEY=${{ secrets.FIGMA_FILE_KEY }} PLATFORM=${{github.event.client_payload.platform}} npm run build:icon
          # アイコンが生成されたディレクトリの内容をリストアップ（デバッグ用）
          echo "Listing contents of the expected directory:"
          ls -la ./src/PBaseNavi/

      # "nogson/takePR"リポジトリをチェックアウト
      - name: Checkout takePR's repo
        uses: actions/checkout@v3
        with:
          repository: "nogson/takePR"
          token: ${{ steps.generate_token.outputs.token }}
          fetch-depth: 0
          path: "takePR"

      # 更新されたアイコンを"nogson/takePR"リポジトリにコピー
      - name: Copy updated icons to takePR's repo
        run: cp -R ./src/PBaseNavi/* takePR/
      # プルリクエストの作成
      - name: Create Pull Request to takePR's repo
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
          commit-message: "Update from makePR"
          title: "Update from makePR"
          body: "This is an automated PR to update content"
          branch: "update-from-makePR"
          path: "takePR"
